### ISSUE TITLE
Running docker build fails

### ISSUE THREAD

**Issue by paulkarikari** [OpenMined/PyDP#100]
### Expected Behavior

Building a docker image from the Dockerfile should not require changes on the host machine.

### Current Behavior
Currently, building a docker image from the Dockerfile fails and it's required to run:
 ```
git submodule init
git submodule update
```

### Steps to Reproduce Behavior

From the project directory run:
`sudo docker build -t pydb . `

### Logs

```
grep: ./third_party/pybind11_bazel/python_configure.bzl: No such file or directory
sed: can't read ./third_party/pybind11_bazel/python_configure.bzl: No such file or directory
sed: can't read ./third_party/pybind11_bazel/python_configure.bzl: No such file or directory
sed: can't read ./third_party/pybind11_bazel/python_configure.bzl: No such file or directory
sed: can't read ./third_party/pybind11_bazel/python_configure.bzl: No such file or directory
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
ERROR: error loading package '': Label '//third_party/pybind11_bazel:python_configure.bzl' is invalid because 'third_party/pybind11_bazel' is not a package; perhaps you meant to put the colon here: '//third_party:pybind11_bazel/python_configure.bzl'?
ERROR: error loading package '': Label '//third_party/pybind11_bazel:python_configure.bzl' is invalid because 'third_party/pybind11_bazel' is not a package; perhaps you meant to put the colon here: '//third_party:pybind11_bazel/python_configure.bzl'?
INFO: Elapsed time: 3.884s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
cp: cannot stat './bazel-bin/src/bindings/pydp.so': No such file or directory
cp: cannot stat './bazel-bin/src/bindings/pydp.so': No such file or directory
```

**Comment by chinmayshah99** [comment]
The idea was using Dockerfile for building the project, i.e., compiling your code when you write any code. And that was the reason `ext_source_setup.sh` was removed from dockerfile. 

So the way it currently works is since the previous layers of containers are already cached, the container could just build when we edit anything in src/.

If we add `ext_source_setup.sh somewhere, we need to figure out the way to keep it in cached part of the container.

**Comment by chinmayshah99** [comment]
Need to figure out the way to keep `ext_source_setup.sh` in cached part of the container.

**Comment by paulkarikari** [comment]
Ok. are you already working on it ? or I should give it a shot?
