### ISSUE TITLE
Documentation for PyDP

### ISSUE THREAD

**Issue by chinmayshah99** [OpenMined/PyDP#107]
We need to start the documentation at `/docs` folder accessible at [here ](pydp.readthedocs.org). 

Before we start the documentation:
1. We need to identify what should be the documentation structure. What should be the template documentation (ex. should we get inspired by how Tensorflow is documented or some other way?)

Once we decide on the template, we should start with the documentation on how to use the library. 

Additionally, #75 also needs to be added in the same documentation structure, in the section contribution guidelines.

**Comment by chinmayshah99** [comment]
Partial work being done at #149

**Comment by chinmayshah99** [comment]
@em-blue We're thinking of using https://www.sphinx-doc.org/en/master/usage/quickstart.html for documentation as it already has in-write support with python code/ pybind11. 

So this requires writing documentation in rst. Was wondering if @OpenMined/writing has a better suggestion?

**Comment by chinmayshah99** [comment]
Done here: 
#207 , #208 , #209 , #210 , #211 , #212

**Comment by 8bitmp3** [comment]
@chinmayshah99 Shall we put/duplicate this Issue in GitHub Projects, since there are a few moving parts here? Then we can assign people and track progress in a "better UI"

**Comment by chinmayshah99** [comment]
PyDP team doesn't use GitHub projects yet, but it would probably be a good idea.
