### ISSUE TITLE
Release: PyDP a0.1.1

### ISSUE THREAD

**Issue by simcof** [OpenMined/PyDP#117]
second alpha release including following features:
<Chinmay to fill in>

**Comment by chinmayshah99** [comment]
The second release will have: 

- Carrots demo working
- Support for all python 3 versions (35, 36, 37)
- If possible all Linux versions too.

**Comment by chinmayshah99** [comment]
Released here: https://github.com/OpenMined/PyDP/releases/tag/v0.1.1dev
