### ISSUE TITLE
Wheel tag doesn't match the actual package

### ISSUE THREAD

**Issue by youben11** [OpenMined/PyDP#119]
### Expected Behavior

The distributed wheel package is tagged with 'py2.py3-none-any' which means it should work on all platform with both python 2 and 3, however, the wheel is including the pydp.so file which is compiled for a specific platform and python3.6 exactly.

### Current Behavior

Can't run on a different platform or python other than 3.6

### Steps to Reproduce Behavior

Install pydp for other version than python3.6, or install it in a different platform than Linux (which the pydp.so file is compiled for)

**Comment by chinmayshah99** [comment]
Similar to #113

**Comment by chinmayshah99** [comment]
Fixed in #133
