### ISSUE TITLE
Error handling for Result, statusor

### ISSUE THREAD

**Issue by chinmayshah99** [OpenMined/PyDP#120]
### Expected Behavior

When we call the result function, which in turn calls `ValueorDie()`, if it dies, it returns a status code with it. 
We need to take that status code from statusorr, integrate with base/status.cpp and raise an error in python.

 ### Current Behavior

When we call the result function, which in turn calls `ValueorDie()`, if it dies, the program crashes

### Steps to Reproduce Behavior

```
>>> import pydp as dp
>>> x = dp.BoundedMean(0.5)
>>> x.result([2,4,4,8])
```
### Logs

```
>>> import pydp as dp
>>> x = dp.BoundedMean(0.5)
>>> x.result([2,4,4,8])
2020-05-02 00:05:16  FATAL  statusor.cc : 38 : Attempting to fetch value instead of handling error kInvalidArgument: Bin count threshold was too large to find approximate bounds. Either run over a larger dataset or decrease success_probability and try again.
2020-05-02 00:05:16  FATAL  statusor.cc : 38 : Attempting to fetch value instead of handling error kInvalidArgument: Bin count threshold was too large to find approximate bounds. Either run over a larger dataset or decrease success_probability and try again.
Aborted (core dumped)
```

### System information

* PyDP version: 0.1.0dev
* Python version: 3.6

**Comment by Harkirat155** [comment]
This doesn't yet seem to handled properly and so neither #188 , for that matter.



> $ pip install -U python-dp
Requirement already up-to-date: python-dp in [PATH]\python38\lib\site-packages (1.0.0)  

>` import pydp `
> ` print(pydp.algorithms.laplacian.BoundedMean(0.9).result()) `
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[PATH]\Python38\lib\site-packages\pydp\algorithms\_algorithm.py", line 126, in result
    return self.__algorithm.partial_result()
RuntimeError: Bin count threshold was too large to find approximate bounds. Either run over a larger dataset or decrease success_probability and try again.

**Comment by chinmayshah99** [comment]
Hi @Harkirat155 ,
Earlier, when this thing used to happen, the python interpreter used to crash, which was what we were trying to solve. Now, it gives a run-time error saying you know what the privacy budget is too less to do this computation.

**Comment by Harkirat155** [comment]
Generally speaking, this could be little hefty. (I got that to work, by trial and error) 
Anyways, would it be possible to
* incorporate a method within the base class of algorithms, that would suggest a viable range of budget to use with the data on such errors,  

This is because  it's getting displayed as an error(hence, there could potentially be a place for an intermediary as was done for the resolution of this issue[introduction  of runtime error]), a poor result on the other hand would have been a different case , it would be handy to just get the range out to the user.

**Comment by chinmayshah99** [comment]
I think this seems to be a fair enhancement that we should do. Can you
create a new issue with the suggestion?

Regards

Chinmay Shah
