### ISSUE TITLE
Split the Style check into two parallel tests

### ISSUE THREAD

**Issue by chinmayshah99** [OpenMined/PyDP#125]
### Expected Behavior

As per the discussion on slack channel, we want to split the style tests into different tests for python and c++. So it becomes easier to understand where the tests fail. 

If possible can we have these two run In parallel, i.e., we want to run both c++ and python style check even if either one of them fails. (Not sure if Github workflows allows that)

### Current Behavior

Right now, all our tests are ran together: https://github.com/OpenMined/PyDP/blob/dev/.github/workflows/style_check.yml

**Comment by codeboy5** [comment]
Steps run sequentially on GitHub actions, different jobs can be run in parallel

**Comment by chinmayshah99** [comment]
Yes, that's the idea. Do you want to take it up?

**Comment by codeboy5** [comment]
I made some changes. https://gist.github.com/codeboy5/3588e71bab1615087b014b4b3a7dccce
I've tested it and it works parallel for both jobs.
Should I open a PR?

**Comment by chinmayshah99** [comment]
Yes, go for it!
