### ISSUE TITLE
Code duplication in C API

### ISSUE THREAD

**Issue by replomancer** [OpenMined/PyDP#150]
There's a lot of code repetition in [c_api.cc](https://github.com/OpenMined/PyDP/blob/8deac51a74382ccf6cc9aeee05aa580634864803/src/bindings/c/c_api.cc) and related files.

We can fix that with templates without hurting performance. Just to make sure we can wait with refactoring until we start benchmarking soon.

**Comment by chinmayshah99** [comment]
C API doesn't support templates. A better idea can be moving to C++ code.

**Comment by replomancer** [comment]
Hey,
This file is actually C++ code :) We even have templates instantiation there already. What makes it "C API" is the `extern "C"` block which prevents C++ style names mangling and allows for C linkage. So it's like this:
```c++
extern "C" {
    // a lot of C++ code
}
```

Wikipedia can probably explain it better: https://en.wikipedia.org/wiki/Compatibility_of_C_and_C%2B%2B#Linking_C_and_C++_code

**Comment by chinmayshah99** [comment]
If that's the case, might just move to C++ code rather than using extern C. extern C allows us to create C bindings for other languages to use it. But since no other team (@OpenMined/dp-research @OpenMined/dp-web-and-mobile, cc @simcof )  has expressed interest, let's move to C++ code.

**Comment by alejandrosame** [comment]
I'll work on this!
