### ISSUE TITLE
Provide version output

### ISSUE THREAD

**Issue by Frank-7** [OpenMined/PyDP#154]
## Feature Description
I would like to get the version of the package when I run `pydp.__version__`

## Is your feature request related to a problem?
Is common practice to provide a way to access the version of each package after importing it using .\_\_version\_\_ after the name of the imported pa

## What alternatives have you considered?
You can look into the version of the package from outside the python prompt

**Comment by systemshift** [comment]
I can't assign myself, but I'll start working on this.
