### ISSUE TITLE
Github actions for Dockerfile

### ISSUE THREAD

**Issue by chinmayshah99** [OpenMined/PyDP#163]
#### Publish to Docker Hub
It would be great if we can push the dockerfile to the docker hub, so users can directly try it from docker hub.

#### Github Action Tests
At the same time, while Github actions do give us in an isolated environment to test our build, we want to check if our build actually doesn't break dockerfile & if possible run the container too to check if it actually works.

Action points:

- [ ] Push to Docker Hub
- [ ] Github Action to test it docker file builds

**Comment by codeboy5** [comment]
Should be use something like this for publishing https://github.com/OpenMined/PySyft/blob/master/.github/workflows/update-docker-image.yml ?Seems good to me
