### ISSUE TITLE
Fix the tests that have been commented out.

### ISSUE THREAD

**Issue by codeboy5** [OpenMined/PyDP#171]
## Description
As part of my recent PR's #168 and #166 to fix the issues with pytest and make them pass, I had to comment out a couple of tests, I've added a TODO in the `tests/algorithms/test_count.py` file and `tests/algorithms/test_distributions.py` file.

Action points:
 - [ ] Fix the tests in `tests/algorithms/test_count.py`
 - [ ] Fix the tests in `tests/algorithms/test_distributions.py`

**Comment by alejandrosame** [comment]
I'll work on this.

**Comment by alejandrosame** [comment]
After the refactor made with #249 the tests were also updated.
