### ISSUE TITLE
Port Restaurant Demo

### ISSUE THREAD

**Issue by chinmayshah99** [OpenMined/PyDP#183]
## Feature Description
Yet another demo is added to the DP library: https://github.com/google/differential-privacy/tree/master/examples/java
We need to port this example using pydp.
Also, jupyter notebook needs to be added for same.

## Additional Context
Experience with Java is required as the original code is written in java.

**Comment by shaistha24** [comment]
I would like to work on it @chinmayshah99

**Comment by chinmayshah99** [comment]
I have assigned it to you @shaistha24

**Comment by bicycleman15** [comment]
@shaistha24 are you still working on this ? I was really interested on working this issue.
If you are still working maybe we can collaborate ?

**Comment by shaistha24** [comment]
@bicycleman15 yes i am working on the jupyter notebook example for this issue. 

Yes, we can definitely collaborate, if possible it would be great if you could start working on the .py code example for the same... Just like we had py code implementation for the carrot demo. 

Is that ok? @bicycleman15 

What is ur slack handle?! Pls reach out on slack for further discussions.

**Comment by chinmayshah99** [comment]
Hey @bicycleman15 how is it coming along?

**Comment by bicycleman15** [comment]
@chinmayshah99 Yes I am working on it, will make a PR soon. 👍

**Comment by chinmayshah99** [comment]
Done in #311 and #324
