### ISSUE TITLE
Add support Slack channel links to main readme file

### ISSUE THREAD

**Issue by tcp** [OpenMined/PyDP#187]
## Where?
Main readme

## Who?
All contributors

## What?
Users of this library should have a good idea of where to get support within Slack so that the general channel does not become a place for people dropping software implementation problems. Please add the following section somewhere in your readme:

```
## Support
For support in using this library, please join the **#lib_pydp** Slack channel. If you’d like to follow along with any code changes to the library, please join the **#code_dp_python** Slack channel. [Click here to join our Slack community!](https://slack.openmined.org)
```

When finished, it should look exactly as it does here: https://github.com/OpenMined/.github/blob/master/README-TEMPLATE.md#support

## Additional Context
None

**Comment by shaistha24** [comment]
Hi @tcp to allow all-contributor to work we need to install and add it to the project first!
 @chinmayshah99 could u pls look into this? After that adding contributors is easy - pls check - how it works -section here https://allcontributors.org/

**Comment by chinmayshah99** [comment]
@shaistha24 Can we add the Support section as @tcp suggested?

**Comment by shaistha24** [comment]
Yes @chinmayshah99 

Also need to install and add all-contributor to the project for contributors section.

@tcp i think we need to add it individually to each openmined project right? Or has it already be attached to OpenMined on the whole?!

**Comment by shaistha24** [comment]
@tcp I have added the support section. Here - https://github.com/OpenMined/PyDP/pull/186

As for the logo the DP team is working with the design team on that!

**Comment by codeboy5** [comment]
> Yes @chinmayshah99
> 
> Also need to install and add all-contributor to the project for contributors section.
> 
> @tcp i think we need to add it individually to each openmined project right? Or has it already be attached to OpenMined on the whole?!

We need to add it separately for each project.

**Comment by ghost** [comment]
addressed

PR added

**Comment by chinmayshah99** [comment]
Closing the issue as it's causing confusion. #186 fixes this

**Comment by tcp** [comment]
Hi everyone! I'm late to this party :)

@chinmayshah99 the only qualm I have is that the `Join Us` section does not point to the channel in Slack. Could you please add this? Don't forget to add the link to each of the Slack channels :)

```
For support in using this library, please join the **#lib_pydp** Slack channel. If you’d like to follow along with any code changes to the library, please join the **#code_dp_python** Slack channel. [Click here to join our Slack community!](https://slack.openmined.org)
```

**Comment by chinmayshah99** [comment]
> Hi everyone! I'm late to this party :)
> 
> @chinmayshah99 the only qualm I have is that the `Join Us` section does not point to the channel in Slack. Could you please add this? Don't forget to add the link to each of the Slack channels :)
> 
> ```
> For support in using this library, please join the **#lib_pydp** Slack channel. If you’d like to follow along with any code changes to the library, please join the **#code_dp_python** Slack channel. [Click here to join our Slack community!](https://slack.openmined.org)
> ```

@shaistha24 please take care of this.
