### ISSUE TITLE
Move from tox to pytest

### ISSUE THREAD

**Issue by chinmayshah99** [OpenMined/PyDP#192]
## Description
For python testing:

We don't need tox anymore as most of our stuff is automated using pytest. And in github actions, each tests are run individually in different python containers, thus pytest would suffice our need.

**Comment by chinmayshah99** [comment]
Work can be picked up from #193 since the person can't take it forward https://github.com/OpenMined/PyDP/pull/193#issuecomment-655950659

**Comment by alejandrosame** [comment]
I can take it from here, since it is also raising an error when following Docker instructions:

```
root@050b6b45660c:~/PyDP# make test-all
tox
make: tox: Command not found
make: *** [Makefile:67: test-all] Error 127
```
