### ISSUE TITLE
Allow setting l0_sensitivity and linf_sensitivity parameters (SetMaxPartitionsContributed, SetMaxContributionsPerPartition)

### ISSUE THREAD

**Issue by replomancer** [OpenMined/PyDP#195]
## Feature Description
Algorithms in PyDP are currently using default values of 1 for l0 sensitivity and linf sensitivity.
The library user needs a way to set these parameters.

## Is your feature request related to a problem?
Restaurant demo cannot be ported to the current version of PyDP with the default l0 sensitivity.
 
## Additional Context
For now these methods are probably enough to use in PyDP:
https://github.com/google/differential-privacy/blob/b351a7f540c7cd8ff1c182ed3d780ebf403c68b0/cc/algorithms/algorithm.h#L212-L222
because I don't think there is any direct access to mechanisms in PyDP.

**Comment by chinmayshah99** [comment]
This seems fairly simple to add.
