### ISSUE TITLE
Introduction to DP

### ISSUE THREAD

**Issue by chinmayshah99** [OpenMined/PyDP#207]
## Where?
Part of our documentation 

## Who?
Someone looking into pydp for the first time

## What?
- Introduction of DP from the basic concepts to technical explanation. // might include pictorial explanation 
- Where one can learn ahead
- Application of DP 
- Where is it currently used 

## Additional Context
Borrowing some text from the DP blog series?

**Comment by TravellerOnCode** [comment]
Hi, I am willing to take this issue.

**Comment by em-blue** [comment]
@chinmayshah99 does this go on the blog or into documentation? just wondering, don't want to duplicate efforts with the privacy series (@Kritikalcoder is leading the DP section of this) https://github.com/orgs/OpenMined/projects/31

**Comment by chinmayshah99** [comment]
Hey @em-blue, @TravellerOnCode did share a draft with me. 
We can include the part that's going in blog to be included in the documentation. 

As a matter of fact, we would love the content that's going in the blog to be included in the documentation and redirect the them to the blog for detailed reading. The only constraint is we want the most of the stuff to be ready before the stable release.

**Comment by 8bitmp3** [comment]
@TravellerOnCode @em-blue If you need some assistance during writing - @ me in your PR 👍 I can also help finish with polishing the differential privacy intro in line with best practices. Happy to help y'all. Cheers! cc @chinmayshah99

**Comment by em-blue** [comment]
@8bitmp3 - amazing, thank you! @chinmayshah99 will keep you in the loop. By the way, I think there's a lot around OpenMined you'd be interested in, want to join us on slack? http://slack.openmined.org
