### ISSUE TITLE
PyDP Introduction

### ISSUE THREAD

**Issue by chinmayshah99** [OpenMined/PyDP#208]
## What?
Introduction to PyDP and what we are we trying to do, including features.

**Comment by ghost** [comment]
I want to work on this!

**Comment by 8bitmp3** [comment]
@oudarjya718 when you're done, let me know - I can help with reviewing the doc. If you need some assistance during writing - ping me 👍 Cheers!

**Comment by ghost** [comment]
@8bitmp3  OK sure!

**Comment by chinmayshah99** [comment]
#254
