### ISSUE TITLE
Laplacian mechanism introduction 

### ISSUE THREAD

**Issue by chinmayshah99** [OpenMined/PyDP#209]
## Who?
Developer who's trying to understand what does it mean when you select laplacian

## What?
Explanation of what choosing Laplacian mechanism for DP means and underlying assumption as well as recommendations on how noise is added and what type of data is desirable. 

## Additional Context
recommend working actively with research team

**Comment by zzzuzum** [comment]
Hi, I'll take this.
Any specific place where this should be written?

**Comment by chinmayshah99** [comment]
It needs to be put in the /docs folder.
@Kritikalcoder seems to be already researching on it. Maybe reach out to her on slack?

**Comment by NateSolon** [comment]
I am working on a Jupyter notebook demo of the Laplacian mechanism, I'm hoping this can be a useful supplement to the documentation: https://github.com/OpenMined/writing/issues/110

**Comment by replomancer** [comment]
I read and executed your notebook @NateSolon  Very clear and easy to follow! I think we should at least include a link to it somewhere in PyDP docs.

**Comment by chinmayshah99** [comment]
#307
