### ISSUE TITLE
Reorganization of Carrots Demo

### ISSUE THREAD

**Issue by chinmayshah99** [OpenMined/PyDP#214]
## Where?
Where are you looking to add documentation? Which file? Which feature?

## Who?
Who is your audience for this documentation issue?

## What?
The current demo https://github.com/OpenMined/PyDP/blob/dev/examples/1.1%20-%20Introductions%20to%20PyDP.ipynb is just a bunch of code and the underlying readme. We want to integrate them into this notebook. 

The motivation is we are gonna add a bunch of tutorials so this just makes it simpler

So our folder structure would look like:
```
tutorial1
  |- tutorial1.ipynb 
  |- file1.py
  |- data.csv
tutorial2
  |- tutorial2.ipynb 
  |- file2.py
  |- data2.csv
```

https://github.com/google/differential-privacy/blob/main/examples/cc/README.md

**Comment by ghost** [comment]
I want to work on this

**Comment by ghost** [comment]
PR opened
