### ISSUE TITLE
Clang-format Not Working 

### ISSUE THREAD

**Issue by codeboy5** [OpenMined/PyDP#215]
## Description
After adding the `clang-format` as a dependency in pipfile, there seems to be a issue while installing It.

## How to Reproduce
Run the `build_PyDP.sh` script.

## Expected Behavior
The package should install without giving any error.

## Screenshots
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/40931412/89099711-e849c200-d40e-11ea-9e0b-656aba12e512.png">

## System Information
 - OS: MacOS \ Linux
 - Language Version: Python 3.7
## Additional Context
We can revert back to the original way `clang-format` was set up.

**Comment by chinmayshah99** [comment]
This is due to clang-format only available on Linux: https://pypi.org/project/clang-format/#files
