### ISSUE TITLE
algorithms\count

### ISSUE THREAD

**Issue by simcof** [OpenMined/PyDP#22]

**Comment by NileshPant1999** [comment]
@simcof will you please elaborate this issue

**Comment by chinmayshah99** [comment]
@NileshPant1999 
This involves wrapping the `algorithms/count.h` with pybind11. 
Find the source code here: https://github.com/google/differential-privacy/blob/master/differential_privacy/algorithms/count.h

**Comment by NileshPant1999** [comment]
We need to write the same function as  https://github.com/google/differential-privacy/blob/master/differential_privacy/algorithms/count.h here

**Comment by alejandrosame** [comment]
I'll work on this issue.
