### ISSUE TITLE
AttributeError: module 'pydp' has no attribute 'StatusOrO'

### ISSUE THREAD

**Issue by devansh1305** [OpenMined/PyDP#226]
## Description
I am getting this error when I try to execute the carrots.py example

## How to Reproduce
1. Go to "PyDP/examples/"
2. Run "Python3 carrots.py"

## Expected Behavior
It should run carrots.py displaying all stats

## Screenshots
![image](https://user-images.githubusercontent.com/30989930/89676982-94c9ef00-d8ba-11ea-8da8-da6a1b28099f.png)

## System Information
 - OS: Ubuntu 18.04.4 LTS
 - OS Version: Ubuntu 18.04.4 LTS
 - Language Version: Python 3.6.9
 
## Additional Context
Looks like there is no definition for StatusOrO variable

**Comment by chinmayshah99** [comment]
Hey @devansh1305, 
Thanks for noting this out. For now, will mostly remove this StatusORO dependency.

**Comment by chinmayshah99** [comment]
The module is worthless standalone, but integrated as mentioned in #233 would serve utility.
