### ISSUE TITLE
Linking of documentation version with setup.cfg

### ISSUE THREAD

**Issue by chinmayshah99** [OpenMined/PyDP#234]
## Description
Using bumpversion, we are able to change the version of python version throughout the codebase. It would be great if we could add  version number in the [documentation](https://github.com/OpenMined/PyDP/blob/dev/docs/conf.py#L66) to [setup.cfg
](https://github.com/OpenMined/PyDP/blob/dev/setup.cfg#L1)

### Additional info
Check on how [bumpvesion](https://pypi.org/project/bumpversion/) works.

**Comment by jandremarais** [comment]
Hi, I haven't used bumpversion before but would like to help. Do I understand correctly that you want to add a file specific configuration for docs/conf.py to setup.cfg like this:
```
[bumpversion:file:docs/conf.py]
search = version="{current_version}"
replace = version="{new_version}"
```
?

**Comment by jandremarais** [comment]
As suggested by @BenjaminDev, the other option is just to replace `version=u"0.1.1` with `version=pydp.__version__` and similarly for `release` (in docs/conf.py). The docs build as expected with it configured this way. Which solution do you think is best?
