### ISSUE TITLE
Add Docerkfile tests in Github Action for every PR

### ISSUE THREAD

**Issue by chinmayshah99** [OpenMined/PyDP#260]
## Feature Description
Our current tests on each commit are only checked on Linux. But sometimes things are broken for Dockerfile in the process. We need to add it as parts of tests for each commit.

**Comment by Vishwaak** [comment]
@chinmayshah99 Can I work on this? If I am right I need to build the docker file for every commit and check the docker image integrity right? This need to added as part of the test.yml file?

**Comment by chinmayshah99** [comment]
Hi @Vishwaak, this can be added as a new .yml file.

**Comment by Vishwaak** [comment]
@chinmayshah99 There seems to a dependence issue when I build the docker image. 
`[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: Could not find a version that matches black (from -r /tmp/pipenv7rysbtoqrequirements/pipenv-mb9dfx_a-constraints.txt (line 2))`

**Comment by chinmayshah99** [comment]
In the docker file, can you try adding `pipenv lock --pre`?

**Comment by Vishwaak** [comment]
@chinmayshah99 That error was due to Black module When we hardcode the module's version then the Docker image seems to be building. So shall I hardcode the Black module version?

**Comment by chinmayshah99** [comment]
Yes, please use the latest availabe version of black.
