### ISSUE TITLE
algorithms\util

### ISSUE THREAD

**Issue by simcof** [OpenMined/PyDP#27]
- [x] XorStrings
- [x] GetNextPowerOfTwo
- [x] Qnorm
- [x] Clamp
- [ ] SafeAdd
- [ ] SafeSquare
- [ ] SafeSubtract
- [ ] Mean
- [ ] StandardDev
- [ ] OrderStatistic
- [ ] Correlation
- [ ] VectorFilter
- [ ] VectorToString

**Comment by chinmayshah99** [comment]
Remaining of these functions needs to be worked out. 
An idea: 
Operator overloading can be done for safeadd, safe subtract.
