### ISSUE TITLE
Moving from Pipenv to Poetry

### ISSUE THREAD

**Issue by chinmayshah99** [OpenMined/PyDP#277]
## Description
Poetry is a much better package manager compared to pipenv, with similarity to package manager in rust & npm. We could migrate. Open to discussions. 

## Additional Context
Poetry: https://python-poetry.org/

**Comment by alejandrosame** [comment]
I'm ok with making a test branch with Poetry tooling to see if it works better for us. Pipenv certainly isn't up to what they promise (yet), it gets too much in the way for little gain.

I don't discard either falling back to plain venv and simply providing targets/actions with our Makefile.

**Comment by chinmayshah99** [comment]
Sounds lika a plan.

Regards

Chinmay Shah

**Comment by alejandrosame** [comment]
@BrendanSchell will work on this
