### ISSUE TITLE
Sphinx in Markdown for improved contributing UX 

### ISSUE THREAD

**Issue by 8bitmp3** [OpenMined/PyDP#282]
Suggestion: Use a Markdown extension in Sphinx, as explained in `https://www.sphinx-doc.org/en/master/usage/markdown.html`, so that we don't have to duplicate work by migrating Markdown to reStructuredText. Example: @chinmayshah99 's https://github.com/OpenMined/PyDP/commit/ac3885f3cdfe5687f1c49b013c4de285b5896c67).

**Comment by 8bitmp3** [comment]
@chinmayshah99 Since more users are probably familiar with Markdown and may feel more comfortable contributing to .md files, let's test the Markdown extension in Sphinx and then start converting reStructuredText files, such as https://github.com/OpenMined/PyDP/blob/dev/docs/introduction.rst.

**Comment by chinmayshah99** [comment]
For conversion, an online tool should do the trick.
We need to add the code in build sphinx so it can support markdown.

Regards

Chinmay Shah
