### ISSUE TITLE
Get rid of Pipenv

### ISSUE THREAD

**Issue by alejandrosame** [OpenMined/PyDP#292]
## What?
For our use case, Pipenv introduces several problems for little gain. We should check how to substitute it.

## Why?
Substituting pipenv means that we need to change code in several setup/admin files. The options considered are:

- [ ] Check moving to Poetry -> #277 
- [ ] If Poetry proves to be also problematic, fallback to **pip+venv** and provide Make targets to make them easy to use and standard.

## Additional Context
This issue is best to be worked on after #289 is solved.

**Comment by BrendanSchell** [comment]
@alejandrosame can I take this on?

**Comment by alejandrosame** [comment]
@BrendanSchell You are more than welcome to take this task :) If you agree, as it is suggested in the description, we can assign you #277 and you can focus on updating the Makefile to substitute pipenv with poetry to begin with.

I hope to not take too long with #289 so these changes can be tested more seamlessly, but is not a hard requirement, it's mostly for convenience. Otherwise, once you make the Makefile targets work with poetry, further updates will be needed on different files around the repository.

**Comment by BrendanSchell** [comment]
@alejandrosame That sounds good to me - I can take on #277 for now to update the Makefile to try out poetry.

**Comment by alejandrosame** [comment]
Hi @BrendanSchell, how is the task going? 

If you have any doubt, do not hesitate to contact us also through Slack, we are quite active there.

**Comment by BrendanSchell** [comment]
@alejandrosame thanks for checking in! Made the change to the makefile and should have some time to test out later today.

**Comment by mhosankalp** [comment]
Hi,

Can I take this one or it is already been worked upon?

Thanks and Regards,
Sankalp

**Comment by alejandrosame** [comment]
Hi @mhosankalp, BrendanSchell is already working on this task!

If you don't find a task to work on, you can always contact us on Slack to see how can we guide you.

**Comment by mhosankalp** [comment]
Thanks @alejandrosame. I will take another one

**Comment by chinmayshah99** [comment]
#310 solves this.
