### ISSUE TITLE
Add Readme for Restaurant Demo 

### ISSUE THREAD

**Issue by shaistha24** [OpenMined/PyDP#313]
## Where?
https://github.com/OpenMined/PyDP/tree/dev/examples/restaurant_demo

## Who?
Anyone checking out the Restaurant demo 

## What?
Add a description for the audience to understand the demo properly. 

## Additional Context
Reference Carrot Demo Readme: https://github.com/OpenMined/PyDP/tree/dev/examples/carrots_demo
Google's readme: https://github.com/google/differential-privacy/tree/main/examples/java

**Comment by mhosankalp** [comment]
Hi, Can I take this one up?

Thanks and Regards,
Sankalp

**Comment by chinmayshah99** [comment]
Hi @mhosankalp, how is this coming along?

**Comment by mhosankalp** [comment]
Hi @chinmayshah99, I have completed it. How can I get it reviewed. As of now I have placed under my GitHub repository. Please see link below:
https://github.com/mhosankalp/Restaurant_Demo

Thanks and Regards,
Sankalp

**Comment by chinmayshah99** [comment]
Hi @mhosankalp this looks great. 
You need to [fork ](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo)the pydp repo. Since this is a readme file, you can [directly upload ](https://docs.github.com/en/free-pro-team@latest/github/managing-files-in-a-repository/adding-a-file-to-a-repository)this file in https://github.com/OpenMined/PyDP/tree/dev/examples/restaurant_demo folder, creating the filename as README.md.

Feel free to reach out on #lib_pydp channel on slack for more help.

**Comment by shaistha24** [comment]
@mhosankalp Hi, I would like to ask you to  mention that it's the PyDP lib version of Google Differential Privacy Lib Java demo Google's readme: https://github.com/google/differential-privacy/tree/main/examples/java

At one glance it looks exactly like Google's Readme which is completely fine, but pls do see that the code snippets and the other materials are shared from PyDP. If you have done so then that's well and good! Else I would like to give gentle reminder to check it.

Also could you pls mention PyDP in the title.

Other than that everything looks great! Nicely done @mhosankalp

**Comment by mhosankalp** [comment]
Hi @shaistha24, Thanks for reviewing. I made sure we have snippet and graph as per PyDp code.I have excluded text which was not relevant to us. I did one more round of review now and I see all the text is as per PyDp Code. Header is also updated to include PyDp. 
Thanks and Regards,
Sankalp

**Comment by chinmayshah99** [comment]
Can you create the PR?

**Comment by mhosankalp** [comment]
@chinmayshah99 have created the PR

**Comment by chinmayshah99** [comment]
Fixed in #324
