### ISSUE TITLE
PyDP Documentation - Add description to the Util

### ISSUE THREAD

**Issue by shaistha24** [OpenMined/PyDP#314]
## Where?
View- https://pydp.readthedocs.io/en/latest/pydp.html#distributions
PyDP Documentation in /doc

## Who?
Contributors and repository maintainers.

## What?
Add a description  for better understanding.

**Comment by festusdrakon** [comment]
Hi guys!
I'd like to work on this issue :D

**Comment by chinmayshah99** [comment]
Sure, assigning it to you.
