### ISSUE TITLE
Add style and mypy checks in jupyter NBs

### ISSUE THREAD

**Issue by chinmayshah99** [OpenMined/PyDP#317]
## Description
Right now the only test for jupyter notebooks is making sure that the notebook actually runs and no code standards test for it. 

We need to add two tests for it: 

- [ ] Style tests

- [ ] Mypy tests for functions

**Comment by 8bitmp3** [comment]
👍 @chinmayshah99 +1 for the (Google) style guide tool to help with linting things up. Maybe you could consider adding this to CI tests for the notebooks. From https://github.com/OpenMined/PyDP/pull/307#pullrequestreview-508552678:

> About linting:
> 
> > The easiest way to scale reviews is to let the machine do it. Every project has recurring issues that pop up in reviews, and style questions are often best settled with a style guide...
> 
> (from this [blog post](https://blog.tensorflow.org/2020/10/how-tensorflow-docs-uses-juypter-notebooks.html) by @lamberta)
> 
> ...
> Then use the `nblint` linter with the `--styles=google` flag:
> 
> `python3 -m tensorflow_docs.tools.nblint  --styles=google your_notebook.ipynb`
> 
> This doesn't highlight everything, but it's good. Check out this [README](https://github.com/tensorflow/docs/blob/master/tools/tensorflow_docs/tools/README.md#nblint) for more options.

**Comment by sid-alluri** [comment]
Is this still available?

**Comment by chinmayshah99** [comment]
Yeah, it is still available. There is some WIP PR: https://github.com/OpenMined/PyDP/pull/322. You can take it forward from there.

**Comment by dnabanita7** [comment]
I made another branch and added tests for all notebooks. The previous PR can be closed.
