### ISSUE TITLE
Error occurs after running tests in docker image.

### ISSUE THREAD

**Issue by siddhesh1598** [OpenMined/PyDP#325]
## Description
After building the image from the docker container, an error occurs after running tests. 

## How to Reproduce
1. Build the image: 
```$ docker build -t pydp:test .```
2. Run the image
```$ docker run --rm -it pydp:test```
3. Run tests
```$ make test```

![Screenshot from 2020-11-07 18-58-16](https://user-images.githubusercontent.com/35634697/98442897-d6726c00-212d-11eb-9e8c-8723d5de03f9.png)

## System Information
 - OS: Linux
 - OS Version: Mint 20.04
 - Language Version: Python 3.8

**Comment by chinmayshah99** [comment]
#310 should solve this :D
