### ISSUE TITLE
Resource unavailable

### ISSUE THREAD

**Issue by pmarangone** [OpenMined/PyDP#329]
## Where?
The last resource cited [here](https://github.com/OpenMined/PyDP/blob/dev/resources.md) isn't available [Bazel and pybind11]

## Additional Context
Is the correct link available?

**Comment by chinmayshah99** [comment]
hey @pmarangone, 
Good catch, here you go: https://github.com/pybind/pybind11_bazel

Can you create a PR with the fix?

**Comment by pmarangone** [comment]
Sure! 
Thank you! :)
