### ISSUE TITLE
Notify users about Python 3.5 deprecation.

### ISSUE THREAD

**Issue by alejandrosame** [OpenMined/PyDP#334]
## Where?
We should let user know that we are dropping support for Python3.5 after the next planned release. At least this warning should appear:
 - in the PyDP pipy page (https://pypi.org/project/python-dp/)
 - as an interactive warning in console when the user does `import pydp` when Python version is 3.5.

## Who?
PyDP package users.

## What?
PyDP users should be encouraged to upgrade their Python to 3.6+ before we stop publishing wheels for it after the next release is out for a smooth transition.

## Additional Context
Many packages are dropping support for Python 3.5 on January 2021, including `pip`which makes this python version out of the common distribution pipelines.
 
We can use as inspiration how other packages communicate Python deprecation like https://pypi.org/project/poetry (both in the pipy page and in the console output).

**Comment by festusdrakon** [comment]
Hey, I'd like to be assigned this issue to work on

**Comment by chinmayshah99** [comment]
Sure
