### ISSUE TITLE
Listed links give '404 Page Not found' (within examples folder)

### ISSUE THREAD

**Issue by rsrinath14** [OpenMined/PyDP#336]
The underlined links (in red) are broken.
![issue1](https://user-images.githubusercontent.com/47494475/103195880-23dab080-4909-11eb-947c-64e178fd1740.jpg)

**Comment by mhosankalp** [comment]
Hi Chinmay,

Can I take this one?

Thanks and Regards,
Sankalp

**Comment by mhosankalp** [comment]
As discussed in the meeting, I will take this one.

**Comment by chinmayshah99** [comment]
Sure
