### ISSUE TITLE
Docs build failing

### ISSUE THREAD

**Issue by chinmayshah99** [OpenMined/PyDP#376]
## Description
Sphinx build action for docs is failing. More on it here: https://github.com/OpenMined/PyDP/runs/3012891718.

You can find the build script here: https://github.com/OpenMined/PyDP/blob/dev/.github/workflows/build-docs.yml

**Comment by dnabanita7** [comment]
I am working on this.

**Comment by chinmayshah99** [comment]
Surprisingly fixed by #394.

**Comment by stoic-signs** [comment]
This was quite a surprise. As I was looking into the issue, I thought we might have to upgrade `libstdc++6 ` on CI.
