### ISSUE TITLE
Remove old submodules

### ISSUE THREAD

**Issue by simcof** [OpenMined/PyDP#40]
The following submodules need to be purged from .git config cache:
/PyBind11 (it has been moved to third_party/PyBind11)
/diffferential-privacy (it has been moved to third_party/differential-privacy)
/third_party/abseil-cpp (this is now configured as a bazel git repository)
/third_party/boringssl (not needed anymore)
/third_party/protobuf (this is now configured as a bazel git repository)

**Comment by jeamick** [comment]
I am working on it
@simcof 

JM

**Comment by chinmayshah99** [comment]
#51 removes pybind11 as a sub-module. 
It's no longer needed as `WORKSPACE` calls `http_archive` for pybind11.

We can close this issue now.
