### ISSUE TITLE
Establish Python package framework

### ISSUE THREAD

**Issue by simcof** [OpenMined/PyDP#41]
- establish .cpp bindings (src/bindings) structure
- establish python extension API

**Comment by chinmayshah99** [comment]
For `src/bindings`, we should follow the same structure as Google DP library.

**Comment by chinmayshah99** [comment]
While we have ported the CPP functions, we need to decide on how the python library will be exactly used. i.e., python API structure and how will the functions like `serialize()` and `partial output()` interact.

**Comment by alejandrosame** [comment]
Should this issue be closed or updated with new requirements?

**Comment by chinmayshah99** [comment]
While #291 talks about organizing the source code, we also need to identify how will we organize the python modules, as we add more modules. Are we going to follow `algorithms.__noise_mechanism__.function` or should we think of a different approach? 

But for all practical purposes at least for now, this issue does not serve utility.
