### ISSUE TITLE
Delta parameter used in algorithms based on the Laplace mechanism

### ISSUE THREAD

**Issue by vdasu** [OpenMined/PyDP#412]
## Question
Why are the algorithms based on the Laplace mechanism using a delta parameter?

## Further Information
If I understand correctly, the Laplace mechanism offers ε-differential privacy. However, the algorithms based on the Laplace mechanism expect the delta parameter as well (E.g. [Max](https://pydp.readthedocs.io/en/latest/pydp.html?highlight=Max#pydp.algorithms.laplacian.Max), [BoundedMean](https://pydp.readthedocs.io/en/latest/pydp.html?highlight=Max#pydp.algorithms.laplacian.BoundedMean)). Issues #410 and #409 are caused because we need to pass delta to the Laplace mechanism algorithms.

**Comment by chinmayshah99** [comment]
Hi @vdasu, This is fixed now. 

Also, The library internally passes a default value as 0 so using named arguments also resolves this.
Just to add on PyDP uses epsilon-delta privacy.
