### ISSUE TITLE
Add contribution guide for  absolute beginners

### ISSUE THREAD

**Issue by soma2000-lang** [OpenMined/PyDP#414]
## Description
There should be a guide for absolute beginners, like how to fork and clone a repository. This will drive new contributors to contribute.

## Are you interested in working on this improvement yourself?
- Yes, I am.

**Comment by chinmayshah99** [comment]
We already have a guide here: https://github.com/OpenMined/PyDP/blob/dev/contributing.md.

Feel free to open the issue if you have something else/ detailed in mind.
