### ISSUE TITLE
Python 3.9 build failing

### ISSUE THREAD

**Issue by chinmayshah99** [OpenMined/PyDP#420]
## Description
Black is failing on python 3.9 all OS types during pytest causing the build to fail.

## How to Reproduce
1. https://github.com/OpenMined/PyDP/runs/7263535015?check_suite_focus=true#step:21:35

**Comment by divyanshugit** [comment]
Hi @chinmayshah99, I would like to work on this.  As of now, my observations on this issue:
 
Cause of the build failure: 
- There is some issue with Poetry's latest version v1.4.0 and the editable dependencies. 

Solutions:
IMO, there are two ways to resolve this issue:
- Fixtate the Poetry's version with some older ones (eg,   `pip install poetry==1.3.2` in all the prereqs file which installs the poetry)
- Make some changes in our setup tool according to the latest version of poetry. (I'll have to look into this)
