### ISSUE TITLE
Can't import pydp 

### ISSUE THREAD

**Issue by menisadi** [OpenMined/PyDP#439]
**System details:** 
Windows 11 AMD64 (64-bit)
Miniconda distribution of python and using conda virtual environment.

**Problem:**
I installed python-dp using pip install python-dp. For some reason it installed version 0.1.0 which is of course causing problem and can't be imported or used.

**Comment by chinmayshah99** [comment]
Hi @menisadi can you explicitly try installing the latest version of pypi: https://pypi.org/project/python-dp/1.1.3rc3/. 
Also, it would be great if you could share some more environment information example python version, windows build version, and the CPU specifications.

**Comment by menisadi** [comment]
I tried it now and I get the following error
```
ERROR: Could not find a version that satisfies the requirement python-dp==1.1.3rc3 (from versions: 0.1.0)
ERROR: No matching distribution found for python-dp==1.1.3rc3
```
My python version is 3.10.8
My Windows version is : 10.0.22621 Build 22621 (Windows 11 Pro)
Processor Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz, 2304 Mhz, 4 Core(s), 8 Logical Processor(s)
System Type	x64-based PC
The model is Dell Vostro 5590

Anything else which might help?

**Comment by chinmayshah99** [comment]
hi @menisadi, just checked there are some issues with our build system. 
We added support for py10 recently but are still facing some issues with windows. 
If you have a WSL, you can start using it immediately.

Immediate solution: You can try using it for python 3.8 if you do not use WSL.

Next steps ahead, we would be fixing our CI/CD process to make sure it supports windows across all python versions. If you are willing to fix it, I can share the probable steps on how we can fix it

**Comment by menisadi** [comment]
I modified the virtual environment to python 3.8, and now it works! Though for some reason it didn't find version 1.1.3rc3 only 1.1.3rc2, so I installed this one.

Thanks!
