### ISSUE TITLE
Maintain Python3 support in all files

### ISSUE THREAD

**Issue by chinmayshah99** [OpenMined/PyDP#56]
In `Makefile `and `tox.ini`, the command invoked is `python file.py`.

The problem is in `conda `env, it defaults to python3. But in systems with both python 2 and 3 installed, it calls python2. 

#### What can be done:
Make sure the correct python version is invoked when you call `python` and make changes accordingly in these two files.

**Comment by karlhigley** [comment]
@chinmayshah99 What would that require? Calling `python3` instead of `python`?

**Comment by Benardi** [comment]
I believe that support to all targeted python versions should be kept via Continuous Integration. By using CI a change / improvement will only be merged into the stable version if it's ensured it supports all targeted versions.

**Comment by chinmayshah99** [comment]
While fixing #57 , setup on system with only python3 env broke. This was fixed in #63 . 
We just need someone to verify that the build process works.
@simcof thoughts?

**Comment by Benardi** [comment]
> While fixing #57 , setup on system with only python3 env broke. This was fixed in #63 .
> We just need someone to verify that the build process works.
> @simcof thoughts?

This problem happens when executing via Makefile ?

**Comment by chinmayshah99** [comment]
> This problem happens when executing via Makefile ?
No. The problem is actually resolved. We just need to test it.
