### ISSUE TITLE
Add support for python 2 and 3 in build config

### ISSUE THREAD

**Issue by simcof** [OpenMined/PyDP#57]
Build config currently defaults to building for python 2 (usually). Need to support multiple configuration

**Comment by TTitcombe** [comment]
Out of interest, why support 2 and 3, given that Python 2 is end of life?

**Comment by chinmayshah99** [comment]
My bad. 
So the idea was in the system with just python3 installed, we can call python by simple `python`, but in the systems with both python 2 and 3, we needed to call python as `python3`. 
Apologies for not making it clear.

**Comment by TTitcombe** [comment]
That makes sense, thanks for clearing that up
