### ISSUE TITLE
Carrots demo

### ISSUE THREAD

**Issue by simcof** [OpenMined/PyDP#59]
Bind enough of the library to execute the carrots demo found in the examples folder of googles DP library

**Comment by jeamick** [comment]
@jeamick

**Comment by chinmayshah99** [comment]
Partial functionality added in https://github.com/OpenMined/PyDP/commit/36bd27b692c53173e1a4632948854bd2b95bf66c.

**Comment by chinmayshah99** [comment]
Added as part of #117
