### ISSUE TITLE
Ensure code adheres to coding standards.

### ISSUE THREAD

**Issue by chinmayshah99** [OpenMined/PyDP#99]
### Expected Behavior

As decided on slack channel, we are following PEP8 style for python and Google code formating for C++. This was pushed in #98 

### Current Behavior

The current code does not adhere to these standards and fails. 

###  How to make it work

- If you type `pycodestyle `in the root directory, you will get list of all errors that needs to fixed. 
- To fix CPP files, make sure that you run clang-format. https://leimao.github.io/blog/Clang-Format-Quick-Tutorial/ might come in handy. 
Following commands needs to fix this,
```
clang-format -i src/bindings/PyDP/*/*.cpp
clang-format -i src/bindings/PyDP/*/*.hpp
```

**Comment by alejandrosame** [comment]
I'll work on this.

**Comment by alejandrosame** [comment]
According to the discussion in the Slack channel, the coding standards will stick to:
  - Using black to enforce Python coding style.
  - Keep the Google clang-format config with a max line length of 88 (80 + 10%, to keep the idea of 90ish from black).

I'll work on making these changes.
